import { Navbar } from "@/components/layout/navbar";
import { Footer } from "@/components/layout/footer";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Play } from "lucide-react";

export default function DemoPage() {
    return (
        <div className="min-h-screen bg-background text-foreground">
            <Navbar />

            <main className="pt-32 pb-20 px-6">
                <div className="max-w-4xl mx-auto text-center mb-16">
                    <h1 className="text-4xl md:text-6xl font-bold font-heading mb-6">See Autorepo in Action</h1>
                    <p className="text-xl text-white/60 max-w-2xl mx-auto">
                        Watch how Autorepo transforms a complex repository into beautiful documentation in seconds.
                    </p>
                </div>

                <div className="max-w-5xl mx-auto">
                    {/* Video Placeholder */}
                    <Card className="aspect-video bg-black/80 flex items-center justify-center relative group cursor-pointer overflow-hidden border-white/10">
                        <div className="absolute inset-0 bg-gradient-to-tr from-violet-600/20 to-purple-600/20 opacity-0 group-hover:opacity-100 transition-opacity" />
                        <div className="h-20 w-20 rounded-full bg-white/10 backdrop-blur-md flex items-center justify-center border border-white/20 group-hover:scale-110 transition-transform">
                            <Play className="h-8 w-8 text-white fill-white ml-1" />
                        </div>
                        <p className="absolute bottom-8 text-white/60 font-medium">Click to watch demo (1:42)</p>
                    </Card>

                    <div className="mt-16 grid md:grid-cols-2 gap-12">
                        <div>
                            <h3 className="text-2xl font-bold mb-4">How it works</h3>
                            <ol className="space-y-6">
                                {[
                                    { title: 'Connect Repository', desc: 'Securely link your GitHub repository via our app.' },
                                    { title: 'AI Analysis', desc: 'Our agents analyze code structure, imports, and comments.' },
                                    { title: 'Context Awareness', desc: 'We understand frameworks (Next.js, Django, etc.) automatically.' },
                                    { title: 'Generate & PR', desc: 'Get a Pull Request with the perfect README.md.' }
                                ].map((step, i) => (
                                    <li key={i} className="flex gap-4">
                                        <div className="h-8 w-8 rounded-full bg-violet-500/20 text-violet-400 flex items-center justify-center font-bold text-sm shrink-0 border border-violet-500/30">
                                            {i + 1}
                                        </div>
                                        <div>
                                            <h4 className="font-bold text-lg">{step.title}</h4>
                                            <p className="text-white/60">{step.desc}</p>
                                        </div>
                                    </li>
                                ))}
                            </ol>
                        </div>
                        <div className="bg-white/5 rounded-2xl p-8 border border-white/10 font-mono text-sm leading-relaxed overflow-hidden">
                            <div className="flex gap-2 mb-4">
                                <div className="h-3 w-3 rounded-full bg-red-500/50" />
                                <div className="h-3 w-3 rounded-full bg-yellow-500/50" />
                                <div className="h-3 w-3 rounded-full bg-green-500/50" />
                            </div>
                            <div className="text-blue-400"># Generated by Autorepo</div>
                            <div className="text-purple-400"># Vertical AI Suite</div>
                            <br />
                            <div className="text-white">## Project Overview</div>
                            <div className="text-white/60">This project implements a high-performance...</div>
                        </div>
                    </div>
                </div>
            </main>
            <Footer />
        </div>
    );
}
